apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sigel-ingress
  namespace: sigel
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [sigel.gob.ec]
      secretName: sigel-tls
  rules:
    - host: sigel.gob.ec
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: gateway, port: { number: 3000 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: web, port: { number: 4000 } }
