apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sigel-staging
namePrefix: stg-
resources:
  - ../../base
patches:
  - target: { kind: Deployment, name: gateway }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: analytics }
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
