-- =============================================================================
-- SIGEL — Seed 02: 24 provincias del Ecuador + 218 cantones (datos electorales 2023)
-- =============================================================================
SET search_path TO sigel, public;

-- Provincias
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('AZU', 'Azuay', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Cuenca', ST_SetSRID(ST_MakePoint(-78.95, -2.9), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('BOL', 'Bolivar', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Guaranda', ST_SetSRID(ST_MakePoint(-79.0, -1.6), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('CAR', 'Carchi', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Tulcán', ST_SetSRID(ST_MakePoint(-77.72, 0.81), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('CAÑ', 'Cañar', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Azogues', ST_SetSRID(ST_MakePoint(-78.95, -2.7), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('CHI', 'Chimborazo', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Riobamba', ST_SetSRID(ST_MakePoint(-78.65, -1.66), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('COT', 'Cotopaxi', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Latacunga', ST_SetSRID(ST_MakePoint(-78.62, -0.93), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('EL ', 'El Oro', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Machala', ST_SetSRID(ST_MakePoint(-79.96, -3.27), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('ESM', 'Esmeraldas', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Esmeraldas', ST_SetSRID(ST_MakePoint(-79.65, 0.96), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('GAL', 'Galapagos', (SELECT id FROM regiones WHERE codigo='INSULAR'), 'Puerto Baquerizo Moreno', ST_SetSRID(ST_MakePoint(-90.95, -0.9), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('GUA', 'Guayas', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Guayaquil', ST_SetSRID(ST_MakePoint(-79.88, -2.19), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('IMB', 'Imbabura', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Ibarra', ST_SetSRID(ST_MakePoint(-78.13, 0.35), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('LOJ', 'Loja', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Loja', ST_SetSRID(ST_MakePoint(-79.2, -3.99), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('LOS', 'Los Rios', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Babahoyo', ST_SetSRID(ST_MakePoint(-79.5, -1.5), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('MAN', 'Manabi', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Portoviejo', ST_SetSRID(ST_MakePoint(-80.45, -1.05), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('MOR', 'Morona Santiago', (SELECT id FROM regiones WHERE codigo='AMAZONIA'), 'Macas', ST_SetSRID(ST_MakePoint(-78.12, -2.31), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('NAP', 'Napo', (SELECT id FROM regiones WHERE codigo='AMAZONIA'), 'Tena', ST_SetSRID(ST_MakePoint(-77.81, -0.92), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('ORE', 'Orellana', (SELECT id FROM regiones WHERE codigo='AMAZONIA'), 'Francisco de Orellana', ST_SetSRID(ST_MakePoint(-76.99, -0.46), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('PAS', 'Pastaza', (SELECT id FROM regiones WHERE codigo='AMAZONIA'), 'Puyo', ST_SetSRID(ST_MakePoint(-77.99, -1.49), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('PIC', 'Pichincha', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Quito', ST_SetSRID(ST_MakePoint(-78.51, -0.22), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('SAN', 'Santa Elena', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Santa Elena', ST_SetSRID(ST_MakePoint(-80.86, -2.23), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('SAN', 'Santo Domingo de los Tsachilas', (SELECT id FROM regiones WHERE codigo='COSTA'), 'Santo Domingo', ST_SetSRID(ST_MakePoint(-79.17, -0.25), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('STO', 'Sto Dgo De los Tsachilas', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Sto Dgo De los Tsachilas', ST_SetSRID(ST_MakePoint(-78.0, -1.0), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('SUC', 'Sucumbios', (SELECT id FROM regiones WHERE codigo='AMAZONIA'), 'Nueva Loja', ST_SetSRID(ST_MakePoint(-76.88, 0.08), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('TUN', 'Tungurahua', (SELECT id FROM regiones WHERE codigo='SIERRA'), 'Ambato', ST_SetSRID(ST_MakePoint(-78.62, -1.25), 4326));
INSERT INTO provincias (codigo_ine, nombre, region_id, capital, centroide) VALUES ('ZAM', 'Zamora Chinchipe', (SELECT id FROM regiones WHERE codigo='AMAZONIA'), 'Zamora', ST_SetSRID(ST_MakePoint(-78.95, -4.07), 4326));

-- GADs provinciales (Prefecturas)
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Azuay', (SELECT id FROM provincias WHERE nombre='Azuay'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Bolivar', (SELECT id FROM provincias WHERE nombre='Bolivar'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Carchi', (SELECT id FROM provincias WHERE nombre='Carchi'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Cañar', (SELECT id FROM provincias WHERE nombre='Cañar'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Chimborazo', (SELECT id FROM provincias WHERE nombre='Chimborazo'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Cotopaxi', (SELECT id FROM provincias WHERE nombre='Cotopaxi'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de El Oro', (SELECT id FROM provincias WHERE nombre='El Oro'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Esmeraldas', (SELECT id FROM provincias WHERE nombre='Esmeraldas'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Galapagos', (SELECT id FROM provincias WHERE nombre='Galapagos'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Guayas', (SELECT id FROM provincias WHERE nombre='Guayas'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Imbabura', (SELECT id FROM provincias WHERE nombre='Imbabura'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Loja', (SELECT id FROM provincias WHERE nombre='Loja'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Los Rios', (SELECT id FROM provincias WHERE nombre='Los Rios'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Manabi', (SELECT id FROM provincias WHERE nombre='Manabi'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Morona Santiago', (SELECT id FROM provincias WHERE nombre='Morona Santiago'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Napo', (SELECT id FROM provincias WHERE nombre='Napo'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Orellana', (SELECT id FROM provincias WHERE nombre='Orellana'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Pastaza', (SELECT id FROM provincias WHERE nombre='Pastaza'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Pichincha', (SELECT id FROM provincias WHERE nombre='Pichincha'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Santa Elena', (SELECT id FROM provincias WHERE nombre='Santa Elena'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Santo Domingo de los Tsachilas', (SELECT id FROM provincias WHERE nombre='Santo Domingo de los Tsachilas'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Sto Dgo De los Tsachilas', (SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Sucumbios', (SELECT id FROM provincias WHERE nombre='Sucumbios'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Tungurahua', (SELECT id FROM provincias WHERE nombre='Tungurahua'));
INSERT INTO gads (tipo, nombre, provincia_id) VALUES ('PROVINCIAL', 'Gobierno Provincial de Zamora Chinchipe', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'));

-- Cantones (extraídos del Excel — 218 registros)
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Camilo Ponce Enriquez');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Chordeleg');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Cuenca');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'El Pan');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Giron');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Guachapala');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Gualaceo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Nabon');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Oña');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Paute');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Pucara');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'San Fernando');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Santa Isabel');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Sevilla de Oro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Azuay'), 'Sigsig');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'Caluma');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'Chillanes');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'Chimbo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'Echeandia');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'Guaranda');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'Las Naves');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Bolivar'), 'San Miguel');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'Azogues');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'Biblian');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'Cañar');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'Deleg');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'El Tambo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'La Troncal');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cañar'), 'Suscal');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Carchi'), 'Bolivar');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Carchi'), 'Espejo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Carchi'), 'Mira');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Carchi'), 'Montufar');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Carchi'), 'San Pedro de Huaca');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Carchi'), 'Tulcan');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'La Mana');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'Latacunga');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'Pangua');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'Pujili');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'Salcedo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'Saquisili');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Cotopaxi'), 'Sigchos');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Alausi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Chambo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Chunchi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Colta');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Cumanda');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Guamote');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Guano');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Pallatanga');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Penipe');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Chimborazo'), 'Riobamba');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Arenillas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Atahualpa');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Balsas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Chilla');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'El Guabo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Huaquillas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Las Lajas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Machala');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Marcabeli');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Pasaje');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Piñas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Portovelo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Santa Rosa');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='El Oro'), 'Zaruma');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'Atacames');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'Eloy Alfaro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'Esmeraldas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'Muisne');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'Quininde');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'Rio Verde');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Esmeraldas'), 'San Lorenzo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'A Baquerizo Moreno');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Balao');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Balzar');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Colimes');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'CRNL Marcelino Maridueñas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Daule');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Duran');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'El Empalme');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'El Triunfo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'GRAL. A Erizalde');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Guayaquil');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Isidro Ayora');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Lomas de Sargentillo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Milagro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Naranjal');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Naranjito');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Nobol/Piedrahita');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Palestina');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Pedro Carbo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Playas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Salitre');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Samborondon');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Santa Lucia');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Simon Bolivar');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Guayas'), 'Yahuachi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Imbabura'), 'Antonio Ante');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Imbabura'), 'Cotacachi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Imbabura'), 'Ibarra');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Imbabura'), 'Otavalo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Imbabura'), 'Pimampiro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Imbabura'), 'Urcuqui');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Calvas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Catamayo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Celica');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Chaguarpamba');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Espindola');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Gonzanama');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Loja');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Macara');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Olmedo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Paltas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Pindal');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Puyango');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Quilanga');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Saraguro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Sozoranga');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Loja'), 'Zapotillo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Baba');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Babahoyo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Buena Fe');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Mocache');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Montalvo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Palenque');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Pueblo Viejo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Quevedo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Quinsaloma');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Urdaneta');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Valencia');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Ventanas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Los Rios'), 'Vinces');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), '24 de Mayo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Bolivar');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Chone');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'El Carmen');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Flavio Alfaro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Jama');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Jaramijo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Jipijapa');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Junin');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Manta');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Montecristi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Olmedo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Pajan');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Pedernales');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Pichincha');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Portoviejo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Puerto Lopez');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Rocafuerte');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'San Vicente');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Santa Ana');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Sucre');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Manabi'), 'Tosagua');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Gualaquiza');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Huamboya');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Limon Indanza');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Logroño');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Morona');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Pablo Sexto');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Palora');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'San Juan Bosco');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Santiago');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Sucua');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Taisha');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Morona Santiago'), 'Tiwintza');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Napo'), 'Archidona');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Napo'), 'C.J. Arosemena Tola');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Napo'), 'El Chaco');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Napo'), 'Quijos');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Napo'), 'Tena');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pastaza'), 'Arajuno');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pastaza'), 'Mera');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pastaza'), 'Pastaza');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pastaza'), 'Santa Clara');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Cayambe');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Mejia');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Pedro Moncayo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Pedro Vicente Maldonado');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Puerto Quito');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Quito');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'Rumiñahui');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Pichincha'), 'San Miguel de los Bancos');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Ambato');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Baños');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Cevallos');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Mocha');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Patate');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Pelileo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Pillaro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Quero');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Tungurahua'), 'Tisaleo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Centinela Del Condor');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Chinchipe');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'El Pangui');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Nangaritza');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Palanda');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Paquisha');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Yacuambi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Yanzatza');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), 'Zamora');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Cascales');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Cuyabeno');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Gonzalo Pizarro');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Lago Agrio');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Putumayo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Shushufindi');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sucumbios'), 'Sucumbios');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Orellana'), 'Aguarico');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Orellana'), 'Fco. De Orellana');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Orellana'), 'Joya de los Sachas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Orellana'), 'Loreto');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas'), 'La Concordia');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas'), 'Santo Domingo');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Santa Elena'), 'La Libertad');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Santa Elena'), 'Salinas');
INSERT INTO cantones (provincia_id, nombre) VALUES ((SELECT id FROM provincias WHERE nombre='Santa Elena'), 'Santa Elena');

-- GADs municipales
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Camilo Ponce Enriquez', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Camilo Ponce Enriquez' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chordeleg', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Chordeleg' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cuenca', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Cuenca' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Pan', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='El Pan' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Giron', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Giron' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Guachapala', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Guachapala' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Gualaceo', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Gualaceo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Nabon', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Nabon' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Oña', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Oña' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Paute', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Paute' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pucara', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Pucara' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Fernando', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='San Fernando' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santa Isabel', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Santa Isabel' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sevilla de Oro', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Sevilla de Oro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sigsig', (SELECT id FROM provincias WHERE nombre='Azuay'), (SELECT id FROM cantones WHERE nombre='Sigsig' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Azuay')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Caluma', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='Caluma' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chillanes', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='Chillanes' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chimbo', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='Chimbo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Echeandia', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='Echeandia' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Guaranda', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='Guaranda' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Las Naves', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='Las Naves' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Miguel', (SELECT id FROM provincias WHERE nombre='Bolivar'), (SELECT id FROM cantones WHERE nombre='San Miguel' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Bolivar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Azogues', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='Azogues' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Biblian', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='Biblian' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cañar', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='Cañar' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Deleg', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='Deleg' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Tambo', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='El Tambo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de La Troncal', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='La Troncal' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Suscal', (SELECT id FROM provincias WHERE nombre='Cañar'), (SELECT id FROM cantones WHERE nombre='Suscal' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cañar')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Bolivar', (SELECT id FROM provincias WHERE nombre='Carchi'), (SELECT id FROM cantones WHERE nombre='Bolivar' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Carchi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Espejo', (SELECT id FROM provincias WHERE nombre='Carchi'), (SELECT id FROM cantones WHERE nombre='Espejo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Carchi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Mira', (SELECT id FROM provincias WHERE nombre='Carchi'), (SELECT id FROM cantones WHERE nombre='Mira' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Carchi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Montufar', (SELECT id FROM provincias WHERE nombre='Carchi'), (SELECT id FROM cantones WHERE nombre='Montufar' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Carchi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Pedro de Huaca', (SELECT id FROM provincias WHERE nombre='Carchi'), (SELECT id FROM cantones WHERE nombre='San Pedro de Huaca' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Carchi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Tulcan', (SELECT id FROM provincias WHERE nombre='Carchi'), (SELECT id FROM cantones WHERE nombre='Tulcan' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Carchi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de La Mana', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='La Mana' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Latacunga', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='Latacunga' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pangua', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='Pangua' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pujili', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='Pujili' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Salcedo', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='Salcedo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Saquisili', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='Saquisili' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sigchos', (SELECT id FROM provincias WHERE nombre='Cotopaxi'), (SELECT id FROM cantones WHERE nombre='Sigchos' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Cotopaxi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Alausi', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Alausi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chambo', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Chambo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chunchi', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Chunchi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Colta', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Colta' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cumanda', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Cumanda' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Guamote', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Guamote' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Guano', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Guano' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pallatanga', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Pallatanga' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Penipe', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Penipe' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Riobamba', (SELECT id FROM provincias WHERE nombre='Chimborazo'), (SELECT id FROM cantones WHERE nombre='Riobamba' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Chimborazo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Arenillas', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Arenillas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Atahualpa', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Atahualpa' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Balsas', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Balsas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chilla', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Chilla' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Guabo', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='El Guabo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Huaquillas', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Huaquillas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Las Lajas', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Las Lajas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Machala', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Machala' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Marcabeli', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Marcabeli' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pasaje', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Pasaje' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Piñas', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Piñas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Portovelo', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Portovelo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santa Rosa', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Santa Rosa' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Zaruma', (SELECT id FROM provincias WHERE nombre='El Oro'), (SELECT id FROM cantones WHERE nombre='Zaruma' AND provincia_id=(SELECT id FROM provincias WHERE nombre='El Oro')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Atacames', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='Atacames' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Eloy Alfaro', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='Eloy Alfaro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Esmeraldas', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='Esmeraldas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Muisne', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='Muisne' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quininde', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='Quininde' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Rio Verde', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='Rio Verde' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Lorenzo', (SELECT id FROM provincias WHERE nombre='Esmeraldas'), (SELECT id FROM cantones WHERE nombre='San Lorenzo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Esmeraldas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de A Baquerizo Moreno', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='A Baquerizo Moreno' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Balao', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Balao' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Balzar', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Balzar' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Colimes', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Colimes' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de CRNL Marcelino Maridueñas', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='CRNL Marcelino Maridueñas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Daule', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Daule' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Duran', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Duran' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Empalme', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='El Empalme' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Triunfo', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='El Triunfo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de GRAL. A Erizalde', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='GRAL. A Erizalde' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Guayaquil', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Guayaquil' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Isidro Ayora', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Isidro Ayora' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Lomas de Sargentillo', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Lomas de Sargentillo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Milagro', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Milagro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Naranjal', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Naranjal' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Naranjito', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Naranjito' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Nobol/Piedrahita', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Nobol/Piedrahita' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Palestina', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Palestina' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pedro Carbo', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Pedro Carbo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Playas', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Playas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Salitre', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Salitre' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Samborondon', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Samborondon' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santa Lucia', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Santa Lucia' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Simon Bolivar', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Simon Bolivar' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Yahuachi', (SELECT id FROM provincias WHERE nombre='Guayas'), (SELECT id FROM cantones WHERE nombre='Yahuachi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Guayas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Antonio Ante', (SELECT id FROM provincias WHERE nombre='Imbabura'), (SELECT id FROM cantones WHERE nombre='Antonio Ante' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Imbabura')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cotacachi', (SELECT id FROM provincias WHERE nombre='Imbabura'), (SELECT id FROM cantones WHERE nombre='Cotacachi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Imbabura')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Ibarra', (SELECT id FROM provincias WHERE nombre='Imbabura'), (SELECT id FROM cantones WHERE nombre='Ibarra' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Imbabura')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Otavalo', (SELECT id FROM provincias WHERE nombre='Imbabura'), (SELECT id FROM cantones WHERE nombre='Otavalo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Imbabura')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pimampiro', (SELECT id FROM provincias WHERE nombre='Imbabura'), (SELECT id FROM cantones WHERE nombre='Pimampiro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Imbabura')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Urcuqui', (SELECT id FROM provincias WHERE nombre='Imbabura'), (SELECT id FROM cantones WHERE nombre='Urcuqui' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Imbabura')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Calvas', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Calvas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Catamayo', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Catamayo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Celica', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Celica' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chaguarpamba', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Chaguarpamba' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Espindola', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Espindola' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Gonzanama', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Gonzanama' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Loja', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Loja' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Macara', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Macara' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Olmedo', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Olmedo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Paltas', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Paltas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pindal', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Pindal' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Puyango', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Puyango' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quilanga', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Quilanga' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Saraguro', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Saraguro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sozoranga', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Sozoranga' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Zapotillo', (SELECT id FROM provincias WHERE nombre='Loja'), (SELECT id FROM cantones WHERE nombre='Zapotillo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Loja')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Baba', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Baba' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Babahoyo', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Babahoyo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Buena Fe', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Buena Fe' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Mocache', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Mocache' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Montalvo', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Montalvo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Palenque', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Palenque' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pueblo Viejo', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Pueblo Viejo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quevedo', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Quevedo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quinsaloma', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Quinsaloma' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Urdaneta', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Urdaneta' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Valencia', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Valencia' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Ventanas', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Ventanas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Vinces', (SELECT id FROM provincias WHERE nombre='Los Rios'), (SELECT id FROM cantones WHERE nombre='Vinces' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Los Rios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de 24 de Mayo', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='24 de Mayo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Bolivar', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Bolivar' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chone', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Chone' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Carmen', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='El Carmen' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Flavio Alfaro', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Flavio Alfaro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Jama', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Jama' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Jaramijo', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Jaramijo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Jipijapa', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Jipijapa' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Junin', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Junin' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Manta', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Manta' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Montecristi', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Montecristi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Olmedo', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Olmedo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pajan', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Pajan' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pedernales', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Pedernales' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pichincha', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Pichincha' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Portoviejo', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Portoviejo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Puerto Lopez', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Puerto Lopez' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Rocafuerte', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Rocafuerte' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Vicente', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='San Vicente' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santa Ana', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Santa Ana' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sucre', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Sucre' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Tosagua', (SELECT id FROM provincias WHERE nombre='Manabi'), (SELECT id FROM cantones WHERE nombre='Tosagua' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Manabi')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Gualaquiza', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Gualaquiza' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Huamboya', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Huamboya' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Limon Indanza', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Limon Indanza' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Logroño', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Logroño' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Morona', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Morona' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pablo Sexto', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Pablo Sexto' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Palora', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Palora' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Juan Bosco', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='San Juan Bosco' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santiago', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Santiago' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sucua', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Sucua' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Taisha', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Taisha' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Tiwintza', (SELECT id FROM provincias WHERE nombre='Morona Santiago'), (SELECT id FROM cantones WHERE nombre='Tiwintza' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Morona Santiago')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Archidona', (SELECT id FROM provincias WHERE nombre='Napo'), (SELECT id FROM cantones WHERE nombre='Archidona' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Napo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de C.J. Arosemena Tola', (SELECT id FROM provincias WHERE nombre='Napo'), (SELECT id FROM cantones WHERE nombre='C.J. Arosemena Tola' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Napo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Chaco', (SELECT id FROM provincias WHERE nombre='Napo'), (SELECT id FROM cantones WHERE nombre='El Chaco' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Napo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quijos', (SELECT id FROM provincias WHERE nombre='Napo'), (SELECT id FROM cantones WHERE nombre='Quijos' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Napo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Tena', (SELECT id FROM provincias WHERE nombre='Napo'), (SELECT id FROM cantones WHERE nombre='Tena' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Napo')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Arajuno', (SELECT id FROM provincias WHERE nombre='Pastaza'), (SELECT id FROM cantones WHERE nombre='Arajuno' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pastaza')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Mera', (SELECT id FROM provincias WHERE nombre='Pastaza'), (SELECT id FROM cantones WHERE nombre='Mera' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pastaza')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pastaza', (SELECT id FROM provincias WHERE nombre='Pastaza'), (SELECT id FROM cantones WHERE nombre='Pastaza' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pastaza')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santa Clara', (SELECT id FROM provincias WHERE nombre='Pastaza'), (SELECT id FROM cantones WHERE nombre='Santa Clara' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pastaza')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cayambe', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Cayambe' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Mejia', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Mejia' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pedro Moncayo', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Pedro Moncayo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pedro Vicente Maldonado', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Pedro Vicente Maldonado' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Puerto Quito', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Puerto Quito' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quito', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Quito' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Rumiñahui', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='Rumiñahui' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de San Miguel de los Bancos', (SELECT id FROM provincias WHERE nombre='Pichincha'), (SELECT id FROM cantones WHERE nombre='San Miguel de los Bancos' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Pichincha')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Ambato', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Ambato' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Baños', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Baños' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cevallos', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Cevallos' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Mocha', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Mocha' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Patate', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Patate' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pelileo', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Pelileo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Pillaro', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Pillaro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Quero', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Quero' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Tisaleo', (SELECT id FROM provincias WHERE nombre='Tungurahua'), (SELECT id FROM cantones WHERE nombre='Tisaleo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Tungurahua')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Centinela Del Condor', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Centinela Del Condor' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Chinchipe', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Chinchipe' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de El Pangui', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='El Pangui' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Nangaritza', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Nangaritza' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Palanda', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Palanda' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Paquisha', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Paquisha' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Yacuambi', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Yacuambi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Yanzatza', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Yanzatza' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Zamora', (SELECT id FROM provincias WHERE nombre='Zamora Chinchipe'), (SELECT id FROM cantones WHERE nombre='Zamora' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Zamora Chinchipe')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cascales', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Cascales' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Cuyabeno', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Cuyabeno' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Gonzalo Pizarro', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Gonzalo Pizarro' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Lago Agrio', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Lago Agrio' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Putumayo', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Putumayo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Shushufindi', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Shushufindi' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Sucumbios', (SELECT id FROM provincias WHERE nombre='Sucumbios'), (SELECT id FROM cantones WHERE nombre='Sucumbios' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sucumbios')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Aguarico', (SELECT id FROM provincias WHERE nombre='Orellana'), (SELECT id FROM cantones WHERE nombre='Aguarico' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Orellana')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Fco. De Orellana', (SELECT id FROM provincias WHERE nombre='Orellana'), (SELECT id FROM cantones WHERE nombre='Fco. De Orellana' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Orellana')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Joya de los Sachas', (SELECT id FROM provincias WHERE nombre='Orellana'), (SELECT id FROM cantones WHERE nombre='Joya de los Sachas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Orellana')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Loreto', (SELECT id FROM provincias WHERE nombre='Orellana'), (SELECT id FROM cantones WHERE nombre='Loreto' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Orellana')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de La Concordia', (SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas'), (SELECT id FROM cantones WHERE nombre='La Concordia' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santo Domingo', (SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas'), (SELECT id FROM cantones WHERE nombre='Santo Domingo' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Sto Dgo De los Tsachilas')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de La Libertad', (SELECT id FROM provincias WHERE nombre='Santa Elena'), (SELECT id FROM cantones WHERE nombre='La Libertad' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Santa Elena')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Salinas', (SELECT id FROM provincias WHERE nombre='Santa Elena'), (SELECT id FROM cantones WHERE nombre='Salinas' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Santa Elena')));
INSERT INTO gads (tipo, nombre, provincia_id, canton_id) VALUES ('MUNICIPAL', 'GAD Municipal de Santa Elena', (SELECT id FROM provincias WHERE nombre='Santa Elena'), (SELECT id FROM cantones WHERE nombre='Santa Elena' AND provincia_id=(SELECT id FROM provincias WHERE nombre='Santa Elena')));
